name: Perf Test

on:
  push:

jobs:
  test_on_manylinux:
    name: Build for manylinux
    runs-on: ubuntu-latest
    container:
      image: docker://quay.io/pypa/manylinux2010_x86_64
    strategy:
      max-parallel: 4
      matrix:
        tp: [0.8.2, 0.8.1, 0.8.0, 0.7.0, 0.7.1, 0.7.0, 0.6.2, 0.5.2, 0.5.1, 0.5.0, 0.4.2, 0.4.0, 0.3.1, 0.3.0, 0.2.0]
        cp: [cp37-cp37m]

    steps:
    - uses: actions/checkout@v1
    - name: Print Info
      run: |
        cat /proc/cpuinfo
    - name: Install dependencies
      run: |
        /opt/python/${{ matrix.cp }}/bin/python -m pip install nltk sklearn
        /opt/python/${{ matrix.cp }}/bin/python -m pip install tomotopy==${{ matrix.tp }}
    - name: Run lda_with_corpus
      continue-on-error: true
      run: |
        /opt/python/${{ matrix.cp }}/bin/python lda_with_corpus.py
    - name: Run lda
      continue-on-error: true
      run: |
        /opt/python/${{ matrix.cp }}/bin/python lda.py
